"""empty message

Revision ID: 486039535fbc
Revises: 69f3d579b8af
Create Date: 2022-07-19 22:43:54.084773

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '486039535fbc'
down_revision = '69f3d579b8af'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('content', sa.Column('password', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('content', 'password')
    # ### end Alembic commands ###
